### PR TITLE
[CMSP-206] Decoupled Preview refactor/coding standards update

### PR DESCRIPTION
**Pull request by jazzsequence**
Cutting it off here and will put more unit tests in a separate PR for CMSP-251.

Walkthrough of these changes is in the [Google Drive](https://drive.google.com/file/d/1ass9zYPHki4pcJPE9BKi1_Rv2u-0YaKY/view?usp=sharing) and far too many individual changes to note here. A [`notes.md`](https://github.com/pantheon-systems/wp-decoupled-preview/blob/b6b25048a4bb26d75662320cf386d5798b3c677b/notes.md) file was added and annotated with the running changes and should be removed prior to deploying to WP.org, but is excluded from the deploy-to-wp workflow if we forget and leave it behind.

### CODE REVIEW

**Review by CdrMarks — DISMISSED** [review]
Rubber stamping this per the walkthrough we had together.

**Comment by jazzsequence** [comment]
@abhisekmazumdar I was reproducing that at one point, but I was able to resolve it. It's possible that didn't make it over to the PR. I can dig into it as well.

**Comment by jazzsequence** [comment]
Update: @abhisekmazumdar check out these lines in my other PR: https://github.com/pantheon-systems/wp-decoupled-preview/pull/17/files#diff-3920a1cba10afe84a7ddb2728da522afdcd264fe22ef4b9bc4e0d6bec8f839c2L668-R696

That might be the thing that's breaking the link/dropdown.

**Comment by backlineint** [comment]
@jazzsequence your update did fix the issue @abhisekmazumdar mentioned, but exposes a new regression. Here are the steps I followed:

* Disable the plugin
* Change to the main branch.
* Activate the plugin
* Edit the hello world post.
* Select 'Example Next.js Preview' from the Decoupled Preview menu button.
* Note that the link leads to https://decoupled-wordpress-dev-sandbox.lndo.site/hello-world/?preview_id=1&preview_nonce=d974c6b74a&decoupled_preview_site=1&preview=true
* Confirm that you are redirected to https://example.com/api/preview?secret=jtq1aESkjb&uri=hello-world&id=28&content_type=post

* Disable the plugin
* Change to the cmsp-206 branch.
* Activate the plugin
* Edit the hello world post.
* Select 'Example Next.js Preview' from the Decoupled Preview menu button.
* Note that the link leads to https://decoupled-wordpress-dev-sandbox.lndo.site/hello-world/?preview_id=1&preview_nonce=d974c6b74a&decoupled_preview_site=1&preview=true
* Note that the redirect fails, resulting in a 'There has been a critical error on this website.' message in WordPress.

Guessing here, but my first thought is that something related to the nonce refactoring is causing this.

I merged the tests into this branch - they looked (and ran) great.

**Review by backlineint — CHANGES_REQUESTED** [review]
Added a comment in the conversation, but I'm now seeing a regression related to the preview redirect.

**Comment by jazzsequence** [comment]
@backlineint I wasn't able to test the preview at all as I was never able to get a working preview site set up. I would rather not hold up the changes/refactor being merged on this bug as it would likely take me longer to figure out what the issue is as I didn't write the original functionality and am less clear on how it's supposed to work. I'm happy to pair/rubber duck with you or @abhisekmazumdar to work through the issue, though.

**Comment by backlineint** [comment]
> I wasn't able to test the preview at all as I was never able to get a working preview site set up.

Debugging this issue shouldn't require a functioning preview site or a front-end site that you control. The default install creates an example preview configuration. If the plugin successfully redirects to that URL, we've solved the regression. Right now all redirects fail with a 'There has been a critical error on this website.' message in WordPress.

> I would rather not hold up the changes/refactor being merged on this bug as it would likely take me longer to figure out what the issue is as I didn't write the original functionality and am less clear on how it's supposed to work. 

We can't merge this in the current state as it breaks the core functionality of the plugin.

> I'm happy to pair/rubber duck with you or @abhisekmazumdar to work through the issue, though.

I'll set up some time.

**Pull request merged**
